"""Build the offline review page and tabular working inventory (standard library)."""
from pathlib import Path
import json, csv, html, hashlib
from collections import Counter
from current_state import current_state
R=Path(__file__).resolve().parents[1]
m=json.loads((R/'evidence/reconstruction.json').read_text())
v=json.loads((R/'evidence/validation.json').read_text())
# Keep the tabular net and gap views synchronized with the exported model.
with (R/'evidence/proposed_nets.csv').open('w',newline='',encoding='utf-8') as f:
    w=csv.writer(f);w.writerow(['net','status','endpoints','retained_original_fragments'])
    for n in sorted(m['nets'],key=lambda n:n['net']):w.writerow([n['net'],n['status'],';'.join(n['endpoints']),';'.join(n.get('original_fragments',[]))])
components={c['ref']:c for c in m['components']}
with (R/'evidence/unresolved_pins.csv').open('w',newline='',encoding='utf-8') as f:
    w=csv.writer(f);w.writerow(['original_ref','pin','reason'])
    for ep in m['unresolved_pins']:
        ref,pin=ep.rsplit('.',1);w.writerow([ref,pin,'Unpopulated footprint' if components[ref]['population']=='DNP' else 'Trace / function unresolved; no certified NC flag'])
status=current_state()
(R/'evidence/completion_status.json').write_text(json.dumps(status,indent=2)+'\n',encoding='utf-8')
rows=[]
with (R/'evidence/components.csv').open('w',newline='',encoding='utf-8') as f:
    fields=['original_ref','kicad_ref','observed_value','proposed_value','marking','population','source','hypothesis','unresolved_pin_count','library_symbol','footprint']
    wr=csv.DictWriter(f,fieldnames=fields);wr.writeheader()
    for c in m['components']:
        d=dict(original_ref=c['ref'],kicad_ref=m['reference_map'].get(c['ref'],c['ref']),observed_value=c['value'],proposed_value=c.get('proposed_value',c['value']),marking=c.get('marking',''),population=c.get('population',''),source=c.get('source',''),hypothesis=c.get('hypothesis','See reconstruction notes; added connectivity inferred'),unresolved_pin_count=sum(e.startswith(c['ref']+'.') for e in m['unresolved_pins']))
        d['library_symbol']=c.get('library_symbol','');d['footprint']=c.get('footprint','');wr.writerow(d);photos=' '.join(f'<a href="photos/originals/{html.escape(p)}">{html.escape(p)}</a>' for p in d['source'].split(';') if p)
        rows.append('<tr>'+''.join('<td>'+html.escape(str(d[k]))+'</td>' for k in fields[:6])+f'<td>{photos}</td><td>{html.escape(d["hypothesis"])}</td></tr>')
esc=html.escape
railrows=''.join('<tr><td><b>'+esc(r['name'])+'</b></td><td>'+esc(r['board_label'])+'</td><td>'+esc(r['path'])+'</td></tr>' for r in status['rails'])
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PetSafe PCB - current reconstruction</title>
<style>*{{box-sizing:border-box}}body{{margin:0;background:#f4f5f3;color:#1c2e2c;font:15px/1.55 system-ui}}main{{max-width:1500px;margin:auto;padding:32px}}h1{{font-size:36px}}h2{{margin-top:30px}}a{{color:#006d64}}nav{{display:flex;flex-wrap:wrap;gap:10px;margin:24px 0}}nav a,button{{border:1px solid #bdd0ca;background:white;padding:9px 14px;border-radius:7px;text-decoration:none;color:#164d44}}.metrics{{display:flex;gap:12px;flex-wrap:wrap}}.metrics div{{padding:17px 20px;background:white;border:1px solid #dce5e0;border-radius:9px}}.metrics strong{{display:block;font-size:28px}}.toolbar{{display:flex;gap:15px;align-items:center;padding:12px;background:#e5ece7;margin-top:25px}}.viewer{{width:100%;max-height:85vh;overflow:auto;background:white;border:1px solid #d3dfd8}}.viewer img{{display:block;width:100%;max-width:none}}.note{{background:#fff1cc;padding:18px}}table{{border-collapse:collapse;background:white;width:100%;font-size:13px}}th,td{{padding:10px;border-bottom:1px solid #d5e0da;text-align:left;vertical-align:top}}th{{position:sticky;top:0;background:#e6ede8}}.scroll{{overflow:auto;max-height:650px}}input[type=search]{{padding:12px;width:100%;max-width:600px;margin:15px 0}}footer{{margin-top:30px;color:#586d66}}</style>
<main><p>PetSafe PPA19-16811 / 100-1339 R03 A | {esc(m['revision'])}</p><h1>Current schematic and remaining work</h1><p>One A2 sheet, grouped into functional blocks. Confirmed measurements, visible copper and application-based hypotheses are kept distinct. The investigation history is preserved separately.</p>
<nav><a href="docs/FINISHING_MEASUREMENTS.html">Next measurements with photos</a><a href="docs/FINISHING_CHECKLIST.html">Current completion checklist</a><a href="output/pdf/PetSafe_completion_status.pdf">Printable status and PIC map</a><a href="output/pdf/PetSafe_single_sheet.pdf">Schematic PDF</a><a href="schematic/PetSafe_1001339.kicad_sch">Native KiCad schematic</a><a href="docs/VIA_REVIEW.html">Via viewer</a><a href="docs/VIA_PAIR_TESTS.html">Via-pair results</a><a href="docs/MEASUREMENTS.md">Measurements</a><a href="docs/SOURCES.md">Sources</a><a href="docs/history/README.md">History</a></nav>
<div class="metrics"><div><strong>{status['catalog_entries']}</strong>catalog entries drawn</div><div><strong>{len(status['current_gpio_pins'])}</strong>PIC pads without a local net</div><div><strong>{len(status['current_fitted_open_pads'])}</strong>open populated-entry pads</div><div><strong>{len(status['unknown_ceramic_values'])}</strong>ceramic values unknown</div><div><strong>{status['footprints']['assigned']} / {status['catalog_entries']}</strong>candidate footprints assigned</div></div>
<p class="note"><b>Still a working reconstruction:</b> {status['modeled_nets']} modeled nets match the native file. ERC has {status['erc_total']} findings: {status['erc_by_type'].get('pin_not_connected',0)} open pads, {status['erc_by_type'].get('isolated_pin_label',0)} isolated labels and {status['erc_by_type'].get('power_pin_not_driven',0)} undriven power inputs. {len(status['current_dnp_open_pads'])} open pads are on empty options. These counts do not capture all inferred wires. No routed PCB or powered functional validation exists.</p>
<h2>Power rails, using the board labels</h2><table><thead><tr><th>Net</th><th>PCB label</th><th>Connection</th></tr></thead><tbody>{railrows}</tbody></table><p>L1 and L2 share VSYS on their supply sides. Their opposite ends remain separate filter outputs. H_RF_VDD, H_LDO_IN, H_RX_VDD and H_PIR_VDD are descriptive local branch names, not additional confirmed independent supply sources. Actual rail voltages are not yet measured.</p>
<h2>Next useful work</h2><p><b>U6A option completed:</b> All three pads are mapped: input after R37, J3 pin 1/PIR supply, and the newly confirmed lower-right GND pad. It remains unpopulated (KiCad reference U106).</p><p><b>J6/Q9 and button update:</b> All five formerly open option pads are mapped from your annotation. R35/R36/Q9/J6 remain unpopulated. S1 upper-right joins the grounded C35 end; lower-right joins R40/C35/R41. R41's opposite end now reaches J1 VPP, confirmed by you. The physical switch-row mapping is corrected; contact behavior remains inferred.</p><p><b>Latest receiver correction:</b> R47/C42 option pads are now wired from the annotated/original photos. R25 lower and R48 right join RX_STAGE_LINK, replacing the older GND and VREF assumptions. C42 upper ground is photo-inferred; both options remain DNP. No new meter reading is implied.</p><p class="note"><b>Latest bench results applied:</b> D6 anode is GND and cathode is VPP (1 ohm routing; 0.7V forward, reverse OL). U6 pin5 joins VIN at 1 ohm; pin4 is unused by user/photo evidence. <a href="docs/FINISHING_MEASUREMENTS.html">All readings recorded; no repeat requested.</a> TP9 remains an unlocated inventory entry pending audit.</p><p><a href="docs/ARCHITECT_REVIEW_RESPONSE.md">Architect review response: J1 corrected, live checks fixed, circuit warnings recorded</a>.</p><p>D3 rail association is resolved: D3.R reaches VDD through V082 and D3.L is GND; D3.S-to-R42 reads 1.2 ohm. The <a href="docs/FINISHING_MEASUREMENTS.html">finishing photo guide</a> records all five batches and the extra reading: U3.5 is VREF, J3.3 is GND, J3.2 reaches R38 K/right, R22 E/right is GND, and U3.6 reaches R23 B/left. R23 C/right joins C40 lower and R42 upper at 1 ohm each. C40 has been removed from its old inferred output grouping. TP16 to TP11/TP17 each read 400 kohm and are rejected as direct joins. All U7 pads now map to J3 (1-to-3, 2-to-2, 3-to-1). PIC21/RB0 now reaches TP16/Q2.S. TP16-VREF measured 0.8 Mohm and the user explicitly withdrew the mistaken PIC21-VREF report. The schematic and via map are corrected. The latest user annotation also resolves C26 to PIC3/RA1 (R28/R29/TP7 net), with C25 remaining PIC2/RA0 and their common ends at GND. Their capacitance values remain unknown. C6 also now parallels C5 across H_RF_VDD/GND, supported by the supplied and original board photos. No new resistance or capacitance measurement is implied; the Q8 supply-path question remains separate. No more PIR-to-PIC routing tests are needed. The agent resolves clear visible copper and reserves measurements for hidden routing, contact behavior or conflicting evidence. Then finish one complete tuning cell and the remaining signal paths before values. D2 local wiring is resolved; its exact identity remains qualified. The <a href="docs/FINISHING_CHECKLIST.html">completion checklist</a> gives each known uncertainty an ID, evidence, next check and closure criterion. No broad via-pair sweep is pending.</p>
<div class="toolbar"><button id="fit">Fit sheet</button><label>Zoom <input id="zoom" type="range" min="100" max="500" value="100" step="25"></label><output id="zvalue">100%</output><a href="output/svg/PetSafe_1001339.svg">Open SVG</a></div><div class="viewer"><img id="drawing" src="output/svg/PetSafe_1001339.svg" alt="Single-sheet KiCad reconstruction"></div>
<h2>Searchable component inventory</h2><p>Observed markings and proposed values are separate. Candidate pin maps use 20 stock and 4 authorized custom symbol definitions. <a href="docs/LIBRARIES_AND_ALTERNATIVES.md">Libraries and alternatives</a> | <a href="docs/RECONSTRUCTION.md">Circuit interpretation</a> | <a href="photo-atlas-v01.html">Original photo atlas</a></p>
<input id="search" type="search" aria-label="Filter components" placeholder="Find U6, Q8, DNP, a photograph..."><div class="scroll"><table><thead><tr><th>Original ref</th><th>KiCad ref</th><th>Observed</th><th>Proposed</th><th>Marking</th><th>Population</th><th>Photos</th><th>Reasoning</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div>
<footer>Original ZIP and photographs preserved. <a href="evidence/validation.json">Native validation</a> | <a href="evidence/proposed_nets.csv">All modeled nets</a> | <a href="evidence/remaining_work.json">Question register</a> | <a href="https://github.com/kerby2000/PetSafe-PCB">GitHub repository</a></footer></main>
<script>const zoom=document.getElementById('zoom'),drawing=document.getElementById('drawing'),zvalue=document.getElementById('zvalue');function change(){{drawing.style.width=zoom.value+'%';zvalue.textContent=zoom.value+'%'}}zoom.addEventListener('input',change);document.getElementById('fit').onclick=()=>{{zoom.value=100;change()}};document.getElementById('search').oninput=e=>{{const q=e.target.value.toLowerCase();document.querySelectorAll('.scroll tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))}};</script></html>'''
(R/'index.html').write_text(page,encoding='utf-8',newline='\n')
sources=[]
for p in sorted((R/'docs/datasheets').glob('*.pdf')):sources.append(dict(file=p.relative_to(R).as_posix(),bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
(R/'evidence/datasheet_manifest.json').write_text(json.dumps(sources,indent=2),encoding='utf-8',newline='\n')
print('Offline review and working inventory generated.')
