"""Build the offline review page and tabular working inventory (standard library)."""
from pathlib import Path
import json, csv, html, hashlib
R=Path(__file__).resolve().parents[1]
m=json.loads((R/'evidence/reconstruction.json').read_text())
v=json.loads((R/'evidence/validation.json').read_text())
rows=[]
with (R/'evidence/components.csv').open('w',newline='',encoding='utf-8') as f:
    fields=['original_ref','kicad_ref','observed_value','proposed_value','marking','population','source','hypothesis','unresolved_pin_count','library_symbol','footprint']
    wr=csv.DictWriter(f,fieldnames=fields);wr.writeheader()
    for c in m['components']:
        d=dict(original_ref=c['ref'],kicad_ref=m['reference_map'].get(c['ref'],c['ref']),observed_value=c['value'],proposed_value=c.get('proposed_value',c['value']),marking=c.get('marking',''),population=c.get('population',''),source=c.get('source',''),hypothesis=c.get('hypothesis','See reconstruction notes; added connectivity inferred'),unresolved_pin_count=sum(e.startswith(c['ref']+'.') for e in m['unresolved_pins']))
        d['library_symbol']=c.get('library_symbol','');d['footprint']=c.get('footprint','');wr.writerow(d);photos=' '.join(f'<a href="photos/originals/{html.escape(p)}">{html.escape(p)}</a>' for p in d['source'].split(';') if p)
        rows.append('<tr>'+''.join('<td>'+html.escape(str(d[k]))+'</td>' for k in fields[:6])+f'<td>{photos}</td><td>{html.escape(d["hypothesis"])}</td></tr>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PetSafe | Single-sheet reconstruction</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f5f3;color:#1c2e2c;font:15px/1.55 system-ui,sans-serif}main{max-width:1600px;margin:auto;padding:36px 32px}header{display:flex;justify-content:space-between;align-items:start;gap:24px}h1{font-size:36px;letter-spacing:-1.2px;margin:4px 0 12px}h2{margin-top:34px}p{max-width:950px}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:12px;color:#52756c}.tag{padding:7px 13px;background:#f7e9c2;border-radius:24px;white-space:nowrap}nav{display:flex;flex-wrap:wrap;gap:10px;margin:24px 0}a{color:#006d64}nav a,button{display:inline-block;border:1px solid #bdd0ca;background:white;padding:9px 14px;border-radius:7px;text-decoration:none;color:#164d44}button{cursor:pointer}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.metrics div{padding:17px 20px;background:white;border:1px solid #dce5e0;border-radius:9px}.metrics strong{display:block;font-size:30px}.toolbar{display:flex;gap:15px;align-items:center;padding:12px 16px;background:#e5ece7;border-radius:10px 10px 0 0}.viewer{width:100%;max-height:85vh;overflow:auto;background:white;border:1px solid #d3dfd8}.viewer img{display:block;width:100%;max-width:none}.cols{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:white;border:1px solid #dce5e0;border-radius:9px;padding:20px}.card h3{margin-top:0}.note{color:#665828}input[type=search]{padding:12px;width:100%;max-width:600px;border:1px solid #b3c5bd;border-radius:6px;font:inherit}table{border-collapse:collapse;background:white;width:100%;font-size:13px}th,td{padding:10px;border-bottom:1px solid #e1e8e4;text-align:left;vertical-align:top}th{position:sticky;top:0;background:#e6ede8}td:nth-child(7){min-width:160px}td:last-child{min-width:260px}.scroll{overflow:auto;margin-top:15px;max-height:650px}footer{margin-top:35px;color:#66786f;font-size:13px}@media(max-width:700px){main{padding:20px}header{display:block}.metrics{grid-template-columns:1fr 1fr}.cols{grid-template-columns:1fr}h1{font-size:29px}}</style>
<main><header><div><div class="eyebrow">PetSafe PPA19-16811 / 100-1339 R03 A</div><h1>One sheet. Connected circuits.</h1><p>A functional working reconstruction from the supplied photographs, the original capture, and manufacturer datasheets. Wires connect parts within each block; named nets connect blocks.</p></div><span class="tag">v0.3 &middot; inferred circuit</span></header>
<nav><a href="output/pdf/PetSafe_single_sheet.pdf">Vector PDF</a><a href="schematic/PetSafe_1001339.kicad_pro">KiCad project</a><a href="schematic/PetSafe_1001339.kicad_sch">Native schematic</a><a href="docs/RECONSTRUCTION.md">Reasoning &amp; alternatives</a><a href="photo-atlas-v01.html">Original photo atlas</a><a href="docs/SOURCES.md">Datasheets</a><a href="docs/LIBRARIES_AND_ALTERNATIVES.md">Libraries &amp; Western alternatives</a></nav>
<section class="metrics"><div><strong>1</strong>schematic sheet</div><div><strong>150</strong>original catalog entries</div><div><strong>29</strong>retained visual fragments</div><div><strong>63</strong>unresolved physical pins</div></section>
<div class="toolbar"><button id="fit">Fit sheet</button><label>Zoom <input id="zoom" type="range" min="100" max="500" value="100" step="25"></label><output id="zvalue">100%</output><a href="output/svg/PetSafe_1001339.svg" target="_blank">Open full SVG</a></div>
<div class="viewer"><img id="drawing" src="output/svg/PetSafe_1001339.svg" alt="All main-board components in a single KiCad schematic, arranged in functional blocks"></div>
<h2>What changed</h2><div class="cols"><article class="card"><h3>Readable circuit structure</h3><p>Power, PIC/clock/ICSP, motor/button, RF excitation, receive chain, switched antenna capacitance, and PIR interface are grouped together. Logic gates, op-amps, transistors, and passives use conventional circuit symbols. Multi-unit ICs remain on this sheet.</p><p>All symbols come from KiCad 10 libraries and were placed through the MCP server. A crosswalk maps photographed pad names to standard pin numbers; unidentified packages use explicit numbered placeholders.</p></article><article class="card"><h3>Identifications and alternatives</h3><p><b>Western candidates:</b> MCP6002-I/SN for SGM8542; DRV8212PDSGR for a motor-driver redesign. The fitted parts retain their identities. U1/U5 await exact vendor symbols.</p><p><b>U1:</b> S-1200B45 4.5 V LDO is a strong candidate: ABLIC maps PPE to this part and the fourth character to a lot code.</p><p><b>U2:</b> TI SN74LVC2G14DBV is a strong candidate: C14R and the six-lead package match.</p><p><b>Still uncertain:</b> Q8 is probably a dual RF switch; U6 has an LDO versus voltage-supervisor alternative.</p></article></div>
<p class="note"><b>Electrical status:</b> The native KiCad netlist matches the authored model. This validates the file, not the physical circuit. ERC retains 80 open findings: 63 unconnected pins, 14 isolated pin labels and three undriven power checks. Numbered placeholders have passive pins and provide limited electrical checking. No continuity measurements or hardware tests were performed. PIR daughterboard internals and a physical PCB layout are outside this revision.</p>
<h2>Searchable working inventory</h2><p>Observed values stay separate from estimates. A question mark is a candidate, not a measurement. The 150 entries include DNP footprints, test points and named-pad aliases.</p><input id="search" type="search" aria-label="Filter components" placeholder="Find U2, C14R, SGM8542, DNP, a photograph..."><div class="scroll"><table><thead><tr><th>Original ref</th><th>KiCad ref</th><th>Observed value</th><th>Proposed value</th><th>Marking</th><th>Population</th><th>Source photos</th><th>Reasoning</th></tr></thead><tbody>ROWS</tbody></table></div>
<footer>Original ZIP and photos preserved. Native KiCad 10.0.5 PDF/SVG/netlist exports. <a href="evidence/validation.json">Validation record</a> &middot; <a href="evidence/proposed_nets.csv">Proposed nets</a> &middot; <a href="evidence/unresolved_pins.csv">Open pins</a></footer></main>
<script>const zoom=document.getElementById('zoom'),drawing=document.getElementById('drawing'),zvalue=document.getElementById('zvalue');function change(){drawing.style.width=zoom.value+'%';zvalue.textContent=zoom.value+'%'}zoom.addEventListener('input',change);document.getElementById('fit').onclick=()=>{zoom.value=100;change()};document.getElementById('search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))};</script></html>'''
(R/'index.html').write_text(page.replace('ROWS','\n'.join(rows)),encoding='utf-8',newline='\n')
sources=[]
for p in sorted((R/'docs/datasheets').glob('*.pdf')):sources.append(dict(file=p.relative_to(R).as_posix(),bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
(R/'evidence/datasheet_manifest.json').write_text(json.dumps(sources,indent=2),encoding='utf-8',newline='\n')
print('Offline review and working inventory generated.')
