"""Offline front/rear evidence viewer; overlays leave original photographs unchanged."""
from pathlib import Path
import json

R=Path(__file__).resolve().parents[1]
audit=json.loads((R/'evidence/via_audit.json').read_text())
summary=audit['review_summary']
page=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PetSafe | Front and rear via review</title>
<style>*{box-sizing:border-box}body{margin:0;background:#eef3f0;color:#173a34;font:15px/1.5 system-ui}main{max-width:1600px;margin:auto;padding:24px}h1{margin:5px 0;font-size:30px}p{max-width:1150px}.metrics,.views,.controls{display:flex;gap:14px;flex-wrap:wrap}.metrics span{background:white;padding:12px 20px;border:1px solid #c8d7cf;border-radius:8px}.controls{align-items:center;margin:18px 0}button,select,input{font:inherit}button,select{padding:8px;border:1px solid #adc5ba;border-radius:5px;background:white;color:#153f35}button{cursor:pointer}a{color:#087568}.views article{flex:1;min-width:350px;background:#fff;border:1px solid #b9ccc2;border-radius:8px;overflow:hidden}.views h2{font-size:18px;margin:10px 16px}canvas{display:block;width:100%;height:440px;background:#152b25;touch-action:none}#overview{height:170px;border-radius:7px;cursor:crosshair;margin:16px 0}#info{background:white;border-left:5px solid #c87622;padding:14px 20px;min-height:145px}#info h2{margin:0;font-size:21px}#info p{margin:4px 0}.muted{color:#62776f}.caution{background:#fff1d4;padding:12px 16px;border-radius:7px}details{margin:18px 0}table{border-collapse:collapse;width:100%;background:white;font-size:13px}td,th{text-align:left;border-bottom:1px solid #dbe4df;padding:8px}th{background:#dce9e1}.table{max-height:420px;overflow:auto}tr[data-id]{cursor:pointer}tr[data-id]:hover{background:#e6f4ec}@media(max-width:800px){main{padding:14px}canvas{height:360px}.views article{min-width:100%}}</style>
<main><a href="../index.html">← Schematic review</a> · <a href="VIA_PAIR_TESTS.html"><b>Next: targeted via-pair measurements</b></a><h1>Follow the via through the board</h1>
<p>Matched front and rear photographs, with the rear already mirrored into the front's orientation. Select a reviewed connection or another catalogued rear site. Drag either detail view to inspect the same surrounding area; use zoom for copper clearance.</p>
<div class="metrics"><span><b>ACTIVE_COUNT</b> active sites / CATALOG_COUNT stable IDs</span><span><b>REVIEWED_COUNT</b> IDs reviewed including corrections</span><span><b>CONFLICT_COUNT</b> conflicting site reports held</span><span><b>REJECTED_IDS</b> rejected as not vias</span></div>
<p class="caution"><b>v0.9.6:</b> 120 IDs reviewed; 120 active sites. User confirms V036-V108 (RA3-R14), V037-V102 (RA4-R15), V039-V097 (RA5-R16) and V047-V091 (RC0-R11). All five tuning-control GPIOs are now mapped, including earlier RC6-R13. Only RC2/V049 and RB0/V026 remain open PIC GPIOs. V064-V075 is now confirmed regulated VDD; the exact Q7 terminal remains a photo candidate. All seven capacitor-junction comparisons returned OL and that broad search is stopped. V053-V071 is rejected. V114 is U2.T2 GND, C5 negative and LED common are grounded. Q1.L is reported VDD; regulated versus motor rail choice remains pending. OMITTED_COUNT IDs remain unmentioned, some already photo-matched. Motor VDD and regulated board VDD remain separate. <a href="../output/pdf/PetSafe_completion_status.pdf">Complete status and next checks</a>.</p><p class="caution"><b>Scope:</b> a visible rear clearance separates the pad from that surface copper. It does not identify a buried net or prove four layers. Components, the sticker and solder obscure other sites. Most front markers are approximate projections, not verified trace destinations.</p>
<div class="controls"><label>Show <select id="filter"><option value="all">All ACTIVE_COUNT active sites</option><option value="reviewed">User-reviewed sites</option><option value="conflicts">Conflicts to resolve</option><option value="unknown">Unassigned electrical net</option><option value="omitted">Not in user list</option><option value="rejected">Rejected recognition</option><option value="anchors">10 manually matched anchors</option><option value="REAR_CLEARANCE">Rear clearance</option><option value="MAIN_REAR_COPPER">Main copper candidates</option><option value="OTHER_REAR_REGION">Other regions</option></select></label><label>Site <select id="sites"></select></label><button id="prev">Previous</button><button id="next">Next</button><label>Detail zoom <input id="zoom" type="range" min="0.35" max="2.5" step="0.05" value="0.8"></label><button id="reset">Centre selected site</button><label><input id="markers" type="checkbox" checked> Markers</label></div>
<div id="info"></div><canvas id="overview" aria-label="Rear overview: select a numbered site"></canvas>
<div class="views"><article><h2>Front • original photograph mosaic</h2><canvas id="front" aria-label="Front photo with via overlay"></canvas></article><article><h2>Rear • mirrored to match front</h2><canvas id="rear" aria-label="Rear photo with via overlay"></canvas></article></div>
<p class="muted">Orange: selected site. Green: reviewed ground. Blue: reviewed supply. Red: conflicting report. Purple: unresolved or signal site. Rear appearance is recorded separately from electrical identity. Front circles for unreviewed sites are projections; registration residuals reach approximately 46 pixels on the 12,000-pixel mosaic.</p>
<details><summary>Evidence basis and limitations</summary><p id="basis"></p><p id="coverage"></p><p id="layers"></p><p>The two PIC ground anchors (pins 8 and 19) establish the main rear region as a ground candidate. The power pin 20 pad provides a contrasting isolated site. Separate edge and antenna regions must not be merged with that ground region just because they also look like copper.</p><p><a href="../evidence/via_inventory.csv">Via inventory CSV</a> · <a href="../evidence/via_audit.json">Full evidence JSON</a> · <a href="../photos/front_registered.jpg">Full front mosaic</a> · <a href="../photos/back_mirrored_registered.jpg">Full registered rear mosaic</a></p></details>
<details><summary>Complete catalogued site list</summary><div class="table"><table><thead><tr><th>ID</th><th>Known endpoint</th><th>Rear appearance</th><th>Review status</th><th>Reviewed net</th></tr></thead><tbody id="rows"></tbody></table></div></details></main>
<script>const audit=DATA,all=audit.sites,$=s=>document.querySelector(s),imgs={front:new Image(),rear:new Image()};let active=all.find(s=>s.id==='V001'),offset=[0,0],ready=0;
const manual=s=>!s.front_match.startsWith('PROJECTED'),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const color=s=>s.review_status==='CONFLICT'?'#ff6577':s.net==='H_GND'?'#38eb9a':['H_VBAT','H_VDD'].includes(s.net)?'#4bc7ff':'#dd9fff';
function listed(){let f=$('#filter').value;return all.filter(s=>f==='rejected'?!s.active:s.active&&(f==='all'||f==='reviewed'&&s.user_reports.length||f==='conflicts'&&s.review_status==='CONFLICT'||f==='unknown'&&!s.net||f==='omitted'&&!s.user_reports.length||f==='anchors'&&manual(s)||s.rear_appearance===f))}
function options(){let list=listed();$('#sites').innerHTML=list.map(s=>`<option value="${s.id}">${s.id} — ${escape(s.endpoints.join(', ')||s.rear_appearance)}</option>`).join('');if(!list.includes(active))active=list[0];if(!active)return;$('#sites').value=active.id;select(active.id)}
function select(id){active=all.find(s=>s.id===id);offset=[0,0];$('#sites').value=id;$('#info').innerHTML=`<h2>${active.id} • ${escape(active.endpoints.join(', ')||(active.component_refs?.length?active.component_refs.join(', ')+' (terminal not established)':'Destination not identified'))}</h2><p><b>${escape(active.net||'No electrical net assigned')}</b> · ${escape(audit.categories[active.rear_appearance])}</p><p><b>User:</b> ${escape(active.user_reports.map(r=>r.claim).join('; ')||'Not listed in this round')}</p><p><b>Joined vias:</b> ${escape((active.joined_vias||[]).join(', ')||'none recorded')}</p><p><b>Rejected direct pairs:</b> ${escape((active.excluded_vias||[]).join(', ')||'none recorded')}</p><p><b>Photo candidates:</b> ${escape((active.candidate_endpoints||[]).join(', ')||'none')}</p><p><b>Cross-check:</b> ${escape(active.component_crosscheck||active.note)}</p><p>${escape(active.conflict||'')}</p><p class="muted">Model nets (may be inferred): ${escape(active.modeled_nets.join(', ')||'none')} | ${escape(active.review_status)}</p><p class="muted">${escape(active.front_match)} · ${escape(active.confidence)}</p>`;draw()}
function canvas(id){let c=$(id),r=c.getBoundingClientRect(),d=window.devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;let ctx=c.getContext('2d');ctx.scale(d,d);return[c,ctx,r.width,r.height]}
function ring(ctx,x,y,r,label,selected){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.lineWidth=selected?3:1.5;ctx.strokeStyle=selected?'#ffac41':ctx.strokeStyle;ctx.stroke();if(label){ctx.font='bold 12px system-ui';let w=ctx.measureText(label).width;ctx.fillStyle='#071d18dc';ctx.fillRect(x+9,y-24,w+10,20);ctx.fillStyle=selected?'#ffcb78':'white';ctx.fillText(label,x+14,y-9)}}
function draw(){if(ready<2)return;let zoom=Number($('#zoom').value);for(let side of ['front','rear']){let[c,ctx,w,h]=canvas('#'+side),p=active[side+'_xy'],cx=p[0]+offset[0],cy=p[1]+offset[1];ctx.drawImage(imgs[side],w/2-cx*zoom,h/2-cy*zoom,12000*zoom,2600*zoom);if($('#markers').checked){for(let s of all.filter(s=>s.active)){let q=s[side+'_xy'],x=w/2+(q[0]-cx)*zoom,y=h/2+(q[1]-cy)*zoom;if(x<0||x>w||y<0||y>h)continue;ctx.strokeStyle=color(s);ctx.setLineDash(side==='front'&&!manual(s)?[4,4]:[]);ring(ctx,x,y,s===active?18:9,s===active||zoom>1.2?s.id:'',s===active)}ctx.setLineDash([])}}let[c,ctx,w,h]=canvas('#overview'),z=Math.min(w/12000,h/2600),oy=(h-2600*z)/2;ctx.drawImage(imgs.rear,0,oy,12000*z,2600*z);for(let s of all.filter(s=>s.active)){ctx.strokeStyle=color(s);ring(ctx,s.rear_xy[0]*z,oy+s.rear_xy[1]*z,s===active?9:2,s===active?s.id:'',s===active)}}
$('#filter').onchange=options;$('#sites').onchange=e=>select(e.target.value);$('#zoom').oninput=draw;$('#markers').onchange=draw;$('#reset').onclick=()=>select(active.id);for(let [id,delta] of [['prev',-1],['next',1]])$('#'+id).onclick=()=>{let list=listed(),i=list.indexOf(active);select(list[(i+delta+list.length)%list.length].id)};
for(let side of ['front','rear']){let start=null,c=$('#'+side);c.onpointerdown=e=>{start=[e.clientX,e.clientY,...offset];c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(start){let z=Number($('#zoom').value);offset=[start[2]-(e.clientX-start[0])/z,start[3]-(e.clientY-start[1])/z];draw()}};c.onpointerup=c.onpointercancel=()=>start=null}
$('#overview').onclick=e=>{let r=e.target.getBoundingClientRect(),z=Math.min(r.width/12000,r.height/2600),x=(e.clientX-r.left)/z,y=(e.clientY-r.top-(r.height-2600*z)/2)/z;let nearest=all.filter(s=>s.active).reduce((a,b)=>Math.hypot(a.rear_xy[0]-x,a.rear_xy[1]-y)<Math.hypot(b.rear_xy[0]-x,b.rear_xy[1]-y)?a:b);$('#filter').value='all';options();select(nearest.id)};
$('#rows').innerHTML=all.map(s=>`<tr data-id="${s.id}"><td>${s.id}</td><td>${escape(s.endpoints.join(', '))}</td><td>${escape(s.rear_appearance)}</td><td>${escape(s.review_status)}</td><td>${escape(s.net||'Unknown')}</td></tr>`).join('');$('#rows').onclick=e=>{let tr=e.target.closest('[data-id]');if(tr){$('#filter').value=all.find(s=>s.id===tr.dataset.id).active?'all':'rejected';options();select(tr.dataset.id);$('#info').scrollIntoView()}};
$('#basis').textContent=audit.ground_basis;$('#coverage').textContent=audit.coverage;$('#layers').textContent=audit.layers;
for(let side of ['front','rear']){imgs[side].onload=()=>{ready++;draw()};imgs[side].src='../'+audit[side==='front'?'source_front':'source_rear']}window.onresize=draw;options();</script></html>'''
(R/'docs/VIA_REVIEW.html').write_text(page.replace('ACTIVE_COUNT',str(summary['active_sites'])).replace('CATALOG_COUNT',str(summary['catalogued_ids'])).replace('REVIEWED_COUNT',str(summary['user_reported_ids'])).replace('CONFLICT_COUNT',str(len(summary['conflicts']))).replace('REJECTED_IDS',', '.join(summary['rejected'])).replace('OMITTED_COUNT',str(len(summary['omitted_from_user_list']))).replace('DATA',json.dumps(audit).replace('</','<\\/')),encoding='utf-8')
print('Via review generated:',len(audit['sites']),'sites')
